# ###########################################
# Fichier de propriété de type "properties" #
# ###########################################

bo_url="http://localhost:6405/biprws"
bo_account="administrator"
bo_password="password123 "
# Type d'authentification (secEnterprise, secSAPR3, secWinAD, secLDAP. Par default 'secEnterprise')
bo_authentication="secEnterprise" 

app_name = "My Application "
version = '1.2.3'
debug = true
timeout = 30
valeur_string = toto

# Variable d'environnement
var_env=${PWDTEST}

# Placeholder hiérarchique
placeholder = "My Application_${PWDTEST}"

