# ###########################################
# Fichier de propriété de type "properties" #
# ###########################################

### Authentification sur une plateforme SAP BI ###
bo_url="http://localhost:6405/biprws"
bo_account="administrator"
bo_password="password123 "
# Type d'authentification (secEnterprise, secSAPR3, secWinAD, secLDAP. Par default 'secEnterprise')
bo_authentication="secEnterprise" 


### Paramètres spécifiques au script 'webi_purge_documents' ###
# taille du batch de purge avant pause (sleep) WIPS
batch_size=100
sleep=60

### Requêtes dédiées au CMS
list_all_documents="SELECT SI_ID, SI_CUID, SI_NAME, SI_KIND, SI_PARENTID, SI_PARENT_CUID, SI_PARENT_FOLDER, SI_PARENT_FOLDER_CUID FROM CI_INFOOBJECTS WHERE SI_KIND = 'Webi' AND SI_INSTANCE = 0 AND SI_OWNER != 'System Account'"
list_all_folders="SELECT SI_ID, SI_CUID, SI_NAME, SI_KIND, SI_PARENTID, SI_PARENT_CUID, SI_PARENT_FOLDER, SI_PARENT_FOLDER_CUID, SI_PATH FROM CI_INFOOBJECTS WHERE SI_OWNER != 'System Account' AND SI_KIND IN ('Folder', 'PersonalFolder', 'FavoritesFolder', 'UserFolder')"

### Variables de démo ###
app_name = "My Application "
version = '1.2.3'
debug = true
timeout = 30
valeur_string = toto

# Variable d'environnement
var_env=${PWDTEST}

# Placeholder hiérarchique
placeholder = "My Application_${PWDTEST}"

