# #####################################
# Fichier de propriété de type "YAML" #
# #####################################

### Paramètres spécifiques aux scripts 'webi_purge_*.py' ###
exclude_private_docs: True      # exclusion des documents privés pour webi_purge_all_documents

# Liste des documents (publics ou privés) à exclure de la purge 
exclude_list: [
    'AT9rtSAiIAmNKjdnddkBF.pw',
    'AWyV19k7kqdMhKxvuHCti58.99',
    'AYigZnPSDW51InJ.KSDRj13I'
]